/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppMetadataIndexRouteImport } from './routes/_app.metadata.index'
import { Route as AppDataSourcesIndexRouteImport } from './routes/_app.data-sources.index'
import { Route as AppToolsConnectorsRouteImport } from './routes/_app.tools.connectors'
import { Route as AppToolsAutomationRouteImport } from './routes/_app.tools.automation'
import { Route as AppToolsApiRouteImport } from './routes/_app.tools.api'
import { Route as AppQualityRulesRouteImport } from './routes/_app.quality.rules'
import { Route as AppQualityMonitorRouteImport } from './routes/_app.quality.monitor'
import { Route as AppQualityErrorsRouteImport } from './routes/_app.quality.errors'
import { Route as AppOperationsWorkflowRouteImport } from './routes/_app.operations.workflow'
import { Route as AppOperationsSchedulesRouteImport } from './routes/_app.operations.schedules'
import { Route as AppOperationsManageSchedulesRouteImport } from './routes/_app.operations.manage-schedules'
import { Route as AppOperationsJobsRouteImport } from './routes/_app.operations.jobs'
import { Route as AppOperationsDeliveriesRouteImport } from './routes/_app.operations.deliveries'
import { Route as AppOperationsCreateScheduleRouteImport } from './routes/_app.operations.create-schedule'
import { Route as AppMetadataValidationRouteImport } from './routes/_app.metadata.validation'
import { Route as AppMetadataTemplatesRouteImport } from './routes/_app.metadata.templates'
import { Route as AppInsightsReportsRouteImport } from './routes/_app.insights.reports'
import { Route as AppInsightsDashboardsRouteImport } from './routes/_app.insights.dashboards'
import { Route as AppInsightsAnalyticsRouteImport } from './routes/_app.insights.analytics'
import { Route as AppEntitiesRepresentativesRouteImport } from './routes/_app.entities.representatives'
import { Route as AppEntitiesEntityRouteImport } from './routes/_app.entities.entity'
import { Route as AppDataSourcesOnboardRouteImport } from './routes/_app.data-sources.onboard'
import { Route as AppDataManagementMappingRouteImport } from './routes/_app.data-management.mapping'
import { Route as AppDataManagementLayersRouteImport } from './routes/_app.data-management.layers'
import { Route as AppDataManagementLayerConfigRouteImport } from './routes/_app.data-management.layer-config'
import { Route as AppDataManagementDbMappingRouteImport } from './routes/_app.data-management.db-mapping'
import { Route as AppAdminUsersRouteImport } from './routes/_app.admin.users'
import { Route as AppAdminSettingsRouteImport } from './routes/_app.admin.settings'
import { Route as AppAdminRolesRouteImport } from './routes/_app.admin.roles'
import { Route as AppAdminPermissionsRouteImport } from './routes/_app.admin.permissions'
import { Route as AppAdminHealthRouteImport } from './routes/_app.admin.health'
import { Route as AppAdminAuditRouteImport } from './routes/_app.admin.audit'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppMetadataIndexRoute = AppMetadataIndexRouteImport.update({
  id: '/metadata/',
  path: '/metadata/',
  getParentRoute: () => AppRoute,
} as any)
const AppDataSourcesIndexRoute = AppDataSourcesIndexRouteImport.update({
  id: '/data-sources/',
  path: '/data-sources/',
  getParentRoute: () => AppRoute,
} as any)
const AppToolsConnectorsRoute = AppToolsConnectorsRouteImport.update({
  id: '/tools/connectors',
  path: '/tools/connectors',
  getParentRoute: () => AppRoute,
} as any)
const AppToolsAutomationRoute = AppToolsAutomationRouteImport.update({
  id: '/tools/automation',
  path: '/tools/automation',
  getParentRoute: () => AppRoute,
} as any)
const AppToolsApiRoute = AppToolsApiRouteImport.update({
  id: '/tools/api',
  path: '/tools/api',
  getParentRoute: () => AppRoute,
} as any)
const AppQualityRulesRoute = AppQualityRulesRouteImport.update({
  id: '/quality/rules',
  path: '/quality/rules',
  getParentRoute: () => AppRoute,
} as any)
const AppQualityMonitorRoute = AppQualityMonitorRouteImport.update({
  id: '/quality/monitor',
  path: '/quality/monitor',
  getParentRoute: () => AppRoute,
} as any)
const AppQualityErrorsRoute = AppQualityErrorsRouteImport.update({
  id: '/quality/errors',
  path: '/quality/errors',
  getParentRoute: () => AppRoute,
} as any)
const AppOperationsWorkflowRoute = AppOperationsWorkflowRouteImport.update({
  id: '/operations/workflow',
  path: '/operations/workflow',
  getParentRoute: () => AppRoute,
} as any)
const AppOperationsSchedulesRoute = AppOperationsSchedulesRouteImport.update({
  id: '/operations/schedules',
  path: '/operations/schedules',
  getParentRoute: () => AppRoute,
} as any)
const AppOperationsManageSchedulesRoute =
  AppOperationsManageSchedulesRouteImport.update({
    id: '/operations/manage-schedules',
    path: '/operations/manage-schedules',
    getParentRoute: () => AppRoute,
  } as any)
const AppOperationsJobsRoute = AppOperationsJobsRouteImport.update({
  id: '/operations/jobs',
  path: '/operations/jobs',
  getParentRoute: () => AppRoute,
} as any)
const AppOperationsDeliveriesRoute = AppOperationsDeliveriesRouteImport.update({
  id: '/operations/deliveries',
  path: '/operations/deliveries',
  getParentRoute: () => AppRoute,
} as any)
const AppOperationsCreateScheduleRoute =
  AppOperationsCreateScheduleRouteImport.update({
    id: '/operations/create-schedule',
    path: '/operations/create-schedule',
    getParentRoute: () => AppRoute,
  } as any)
const AppMetadataValidationRoute = AppMetadataValidationRouteImport.update({
  id: '/metadata/validation',
  path: '/metadata/validation',
  getParentRoute: () => AppRoute,
} as any)
const AppMetadataTemplatesRoute = AppMetadataTemplatesRouteImport.update({
  id: '/metadata/templates',
  path: '/metadata/templates',
  getParentRoute: () => AppRoute,
} as any)
const AppInsightsReportsRoute = AppInsightsReportsRouteImport.update({
  id: '/insights/reports',
  path: '/insights/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppInsightsDashboardsRoute = AppInsightsDashboardsRouteImport.update({
  id: '/insights/dashboards',
  path: '/insights/dashboards',
  getParentRoute: () => AppRoute,
} as any)
const AppInsightsAnalyticsRoute = AppInsightsAnalyticsRouteImport.update({
  id: '/insights/analytics',
  path: '/insights/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppEntitiesRepresentativesRoute =
  AppEntitiesRepresentativesRouteImport.update({
    id: '/entities/representatives',
    path: '/entities/representatives',
    getParentRoute: () => AppRoute,
  } as any)
const AppEntitiesEntityRoute = AppEntitiesEntityRouteImport.update({
  id: '/entities/entity',
  path: '/entities/entity',
  getParentRoute: () => AppRoute,
} as any)
const AppDataSourcesOnboardRoute = AppDataSourcesOnboardRouteImport.update({
  id: '/data-sources/onboard',
  path: '/data-sources/onboard',
  getParentRoute: () => AppRoute,
} as any)
const AppDataManagementMappingRoute =
  AppDataManagementMappingRouteImport.update({
    id: '/data-management/mapping',
    path: '/data-management/mapping',
    getParentRoute: () => AppRoute,
  } as any)
const AppDataManagementLayersRoute = AppDataManagementLayersRouteImport.update({
  id: '/data-management/layers',
  path: '/data-management/layers',
  getParentRoute: () => AppRoute,
} as any)
const AppDataManagementLayerConfigRoute =
  AppDataManagementLayerConfigRouteImport.update({
    id: '/data-management/layer-config',
    path: '/data-management/layer-config',
    getParentRoute: () => AppRoute,
  } as any)
const AppDataManagementDbMappingRoute =
  AppDataManagementDbMappingRouteImport.update({
    id: '/data-management/db-mapping',
    path: '/data-management/db-mapping',
    getParentRoute: () => AppRoute,
  } as any)
const AppAdminUsersRoute = AppAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminSettingsRoute = AppAdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRolesRoute = AppAdminRolesRouteImport.update({
  id: '/admin/roles',
  path: '/admin/roles',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminPermissionsRoute = AppAdminPermissionsRouteImport.update({
  id: '/admin/permissions',
  path: '/admin/permissions',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminHealthRoute = AppAdminHealthRouteImport.update({
  id: '/admin/health',
  path: '/admin/health',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminAuditRoute = AppAdminAuditRouteImport.update({
  id: '/admin/audit',
  path: '/admin/audit',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AppDashboardRoute
  '/admin/audit': typeof AppAdminAuditRoute
  '/admin/health': typeof AppAdminHealthRoute
  '/admin/permissions': typeof AppAdminPermissionsRoute
  '/admin/roles': typeof AppAdminRolesRoute
  '/admin/settings': typeof AppAdminSettingsRoute
  '/admin/users': typeof AppAdminUsersRoute
  '/data-management/db-mapping': typeof AppDataManagementDbMappingRoute
  '/data-management/layer-config': typeof AppDataManagementLayerConfigRoute
  '/data-management/layers': typeof AppDataManagementLayersRoute
  '/data-management/mapping': typeof AppDataManagementMappingRoute
  '/data-sources/onboard': typeof AppDataSourcesOnboardRoute
  '/entities/entity': typeof AppEntitiesEntityRoute
  '/entities/representatives': typeof AppEntitiesRepresentativesRoute
  '/insights/analytics': typeof AppInsightsAnalyticsRoute
  '/insights/dashboards': typeof AppInsightsDashboardsRoute
  '/insights/reports': typeof AppInsightsReportsRoute
  '/metadata/templates': typeof AppMetadataTemplatesRoute
  '/metadata/validation': typeof AppMetadataValidationRoute
  '/operations/create-schedule': typeof AppOperationsCreateScheduleRoute
  '/operations/deliveries': typeof AppOperationsDeliveriesRoute
  '/operations/jobs': typeof AppOperationsJobsRoute
  '/operations/manage-schedules': typeof AppOperationsManageSchedulesRoute
  '/operations/schedules': typeof AppOperationsSchedulesRoute
  '/operations/workflow': typeof AppOperationsWorkflowRoute
  '/quality/errors': typeof AppQualityErrorsRoute
  '/quality/monitor': typeof AppQualityMonitorRoute
  '/quality/rules': typeof AppQualityRulesRoute
  '/tools/api': typeof AppToolsApiRoute
  '/tools/automation': typeof AppToolsAutomationRoute
  '/tools/connectors': typeof AppToolsConnectorsRoute
  '/data-sources/': typeof AppDataSourcesIndexRoute
  '/metadata/': typeof AppMetadataIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AppDashboardRoute
  '/admin/audit': typeof AppAdminAuditRoute
  '/admin/health': typeof AppAdminHealthRoute
  '/admin/permissions': typeof AppAdminPermissionsRoute
  '/admin/roles': typeof AppAdminRolesRoute
  '/admin/settings': typeof AppAdminSettingsRoute
  '/admin/users': typeof AppAdminUsersRoute
  '/data-management/db-mapping': typeof AppDataManagementDbMappingRoute
  '/data-management/layer-config': typeof AppDataManagementLayerConfigRoute
  '/data-management/layers': typeof AppDataManagementLayersRoute
  '/data-management/mapping': typeof AppDataManagementMappingRoute
  '/data-sources/onboard': typeof AppDataSourcesOnboardRoute
  '/entities/entity': typeof AppEntitiesEntityRoute
  '/entities/representatives': typeof AppEntitiesRepresentativesRoute
  '/insights/analytics': typeof AppInsightsAnalyticsRoute
  '/insights/dashboards': typeof AppInsightsDashboardsRoute
  '/insights/reports': typeof AppInsightsReportsRoute
  '/metadata/templates': typeof AppMetadataTemplatesRoute
  '/metadata/validation': typeof AppMetadataValidationRoute
  '/operations/create-schedule': typeof AppOperationsCreateScheduleRoute
  '/operations/deliveries': typeof AppOperationsDeliveriesRoute
  '/operations/jobs': typeof AppOperationsJobsRoute
  '/operations/manage-schedules': typeof AppOperationsManageSchedulesRoute
  '/operations/schedules': typeof AppOperationsSchedulesRoute
  '/operations/workflow': typeof AppOperationsWorkflowRoute
  '/quality/errors': typeof AppQualityErrorsRoute
  '/quality/monitor': typeof AppQualityMonitorRoute
  '/quality/rules': typeof AppQualityRulesRoute
  '/tools/api': typeof AppToolsApiRoute
  '/tools/automation': typeof AppToolsAutomationRoute
  '/tools/connectors': typeof AppToolsConnectorsRoute
  '/data-sources': typeof AppDataSourcesIndexRoute
  '/metadata': typeof AppMetadataIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/admin/audit': typeof AppAdminAuditRoute
  '/_app/admin/health': typeof AppAdminHealthRoute
  '/_app/admin/permissions': typeof AppAdminPermissionsRoute
  '/_app/admin/roles': typeof AppAdminRolesRoute
  '/_app/admin/settings': typeof AppAdminSettingsRoute
  '/_app/admin/users': typeof AppAdminUsersRoute
  '/_app/data-management/db-mapping': typeof AppDataManagementDbMappingRoute
  '/_app/data-management/layer-config': typeof AppDataManagementLayerConfigRoute
  '/_app/data-management/layers': typeof AppDataManagementLayersRoute
  '/_app/data-management/mapping': typeof AppDataManagementMappingRoute
  '/_app/data-sources/onboard': typeof AppDataSourcesOnboardRoute
  '/_app/entities/entity': typeof AppEntitiesEntityRoute
  '/_app/entities/representatives': typeof AppEntitiesRepresentativesRoute
  '/_app/insights/analytics': typeof AppInsightsAnalyticsRoute
  '/_app/insights/dashboards': typeof AppInsightsDashboardsRoute
  '/_app/insights/reports': typeof AppInsightsReportsRoute
  '/_app/metadata/templates': typeof AppMetadataTemplatesRoute
  '/_app/metadata/validation': typeof AppMetadataValidationRoute
  '/_app/operations/create-schedule': typeof AppOperationsCreateScheduleRoute
  '/_app/operations/deliveries': typeof AppOperationsDeliveriesRoute
  '/_app/operations/jobs': typeof AppOperationsJobsRoute
  '/_app/operations/manage-schedules': typeof AppOperationsManageSchedulesRoute
  '/_app/operations/schedules': typeof AppOperationsSchedulesRoute
  '/_app/operations/workflow': typeof AppOperationsWorkflowRoute
  '/_app/quality/errors': typeof AppQualityErrorsRoute
  '/_app/quality/monitor': typeof AppQualityMonitorRoute
  '/_app/quality/rules': typeof AppQualityRulesRoute
  '/_app/tools/api': typeof AppToolsApiRoute
  '/_app/tools/automation': typeof AppToolsAutomationRoute
  '/_app/tools/connectors': typeof AppToolsConnectorsRoute
  '/_app/data-sources/': typeof AppDataSourcesIndexRoute
  '/_app/metadata/': typeof AppMetadataIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/dashboard'
    | '/admin/audit'
    | '/admin/health'
    | '/admin/permissions'
    | '/admin/roles'
    | '/admin/settings'
    | '/admin/users'
    | '/data-management/db-mapping'
    | '/data-management/layer-config'
    | '/data-management/layers'
    | '/data-management/mapping'
    | '/data-sources/onboard'
    | '/entities/entity'
    | '/entities/representatives'
    | '/insights/analytics'
    | '/insights/dashboards'
    | '/insights/reports'
    | '/metadata/templates'
    | '/metadata/validation'
    | '/operations/create-schedule'
    | '/operations/deliveries'
    | '/operations/jobs'
    | '/operations/manage-schedules'
    | '/operations/schedules'
    | '/operations/workflow'
    | '/quality/errors'
    | '/quality/monitor'
    | '/quality/rules'
    | '/tools/api'
    | '/tools/automation'
    | '/tools/connectors'
    | '/data-sources/'
    | '/metadata/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard'
    | '/admin/audit'
    | '/admin/health'
    | '/admin/permissions'
    | '/admin/roles'
    | '/admin/settings'
    | '/admin/users'
    | '/data-management/db-mapping'
    | '/data-management/layer-config'
    | '/data-management/layers'
    | '/data-management/mapping'
    | '/data-sources/onboard'
    | '/entities/entity'
    | '/entities/representatives'
    | '/insights/analytics'
    | '/insights/dashboards'
    | '/insights/reports'
    | '/metadata/templates'
    | '/metadata/validation'
    | '/operations/create-schedule'
    | '/operations/deliveries'
    | '/operations/jobs'
    | '/operations/manage-schedules'
    | '/operations/schedules'
    | '/operations/workflow'
    | '/quality/errors'
    | '/quality/monitor'
    | '/quality/rules'
    | '/tools/api'
    | '/tools/automation'
    | '/tools/connectors'
    | '/data-sources'
    | '/metadata'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/dashboard'
    | '/_app/admin/audit'
    | '/_app/admin/health'
    | '/_app/admin/permissions'
    | '/_app/admin/roles'
    | '/_app/admin/settings'
    | '/_app/admin/users'
    | '/_app/data-management/db-mapping'
    | '/_app/data-management/layer-config'
    | '/_app/data-management/layers'
    | '/_app/data-management/mapping'
    | '/_app/data-sources/onboard'
    | '/_app/entities/entity'
    | '/_app/entities/representatives'
    | '/_app/insights/analytics'
    | '/_app/insights/dashboards'
    | '/_app/insights/reports'
    | '/_app/metadata/templates'
    | '/_app/metadata/validation'
    | '/_app/operations/create-schedule'
    | '/_app/operations/deliveries'
    | '/_app/operations/jobs'
    | '/_app/operations/manage-schedules'
    | '/_app/operations/schedules'
    | '/_app/operations/workflow'
    | '/_app/quality/errors'
    | '/_app/quality/monitor'
    | '/_app/quality/rules'
    | '/_app/tools/api'
    | '/_app/tools/automation'
    | '/_app/tools/connectors'
    | '/_app/data-sources/'
    | '/_app/metadata/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/metadata/': {
      id: '/_app/metadata/'
      path: '/metadata'
      fullPath: '/metadata/'
      preLoaderRoute: typeof AppMetadataIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/data-sources/': {
      id: '/_app/data-sources/'
      path: '/data-sources'
      fullPath: '/data-sources/'
      preLoaderRoute: typeof AppDataSourcesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tools/connectors': {
      id: '/_app/tools/connectors'
      path: '/tools/connectors'
      fullPath: '/tools/connectors'
      preLoaderRoute: typeof AppToolsConnectorsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tools/automation': {
      id: '/_app/tools/automation'
      path: '/tools/automation'
      fullPath: '/tools/automation'
      preLoaderRoute: typeof AppToolsAutomationRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tools/api': {
      id: '/_app/tools/api'
      path: '/tools/api'
      fullPath: '/tools/api'
      preLoaderRoute: typeof AppToolsApiRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/quality/rules': {
      id: '/_app/quality/rules'
      path: '/quality/rules'
      fullPath: '/quality/rules'
      preLoaderRoute: typeof AppQualityRulesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/quality/monitor': {
      id: '/_app/quality/monitor'
      path: '/quality/monitor'
      fullPath: '/quality/monitor'
      preLoaderRoute: typeof AppQualityMonitorRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/quality/errors': {
      id: '/_app/quality/errors'
      path: '/quality/errors'
      fullPath: '/quality/errors'
      preLoaderRoute: typeof AppQualityErrorsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/operations/workflow': {
      id: '/_app/operations/workflow'
      path: '/operations/workflow'
      fullPath: '/operations/workflow'
      preLoaderRoute: typeof AppOperationsWorkflowRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/operations/schedules': {
      id: '/_app/operations/schedules'
      path: '/operations/schedules'
      fullPath: '/operations/schedules'
      preLoaderRoute: typeof AppOperationsSchedulesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/operations/manage-schedules': {
      id: '/_app/operations/manage-schedules'
      path: '/operations/manage-schedules'
      fullPath: '/operations/manage-schedules'
      preLoaderRoute: typeof AppOperationsManageSchedulesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/operations/jobs': {
      id: '/_app/operations/jobs'
      path: '/operations/jobs'
      fullPath: '/operations/jobs'
      preLoaderRoute: typeof AppOperationsJobsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/operations/deliveries': {
      id: '/_app/operations/deliveries'
      path: '/operations/deliveries'
      fullPath: '/operations/deliveries'
      preLoaderRoute: typeof AppOperationsDeliveriesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/operations/create-schedule': {
      id: '/_app/operations/create-schedule'
      path: '/operations/create-schedule'
      fullPath: '/operations/create-schedule'
      preLoaderRoute: typeof AppOperationsCreateScheduleRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/metadata/validation': {
      id: '/_app/metadata/validation'
      path: '/metadata/validation'
      fullPath: '/metadata/validation'
      preLoaderRoute: typeof AppMetadataValidationRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/metadata/templates': {
      id: '/_app/metadata/templates'
      path: '/metadata/templates'
      fullPath: '/metadata/templates'
      preLoaderRoute: typeof AppMetadataTemplatesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/insights/reports': {
      id: '/_app/insights/reports'
      path: '/insights/reports'
      fullPath: '/insights/reports'
      preLoaderRoute: typeof AppInsightsReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/insights/dashboards': {
      id: '/_app/insights/dashboards'
      path: '/insights/dashboards'
      fullPath: '/insights/dashboards'
      preLoaderRoute: typeof AppInsightsDashboardsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/insights/analytics': {
      id: '/_app/insights/analytics'
      path: '/insights/analytics'
      fullPath: '/insights/analytics'
      preLoaderRoute: typeof AppInsightsAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/entities/representatives': {
      id: '/_app/entities/representatives'
      path: '/entities/representatives'
      fullPath: '/entities/representatives'
      preLoaderRoute: typeof AppEntitiesRepresentativesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/entities/entity': {
      id: '/_app/entities/entity'
      path: '/entities/entity'
      fullPath: '/entities/entity'
      preLoaderRoute: typeof AppEntitiesEntityRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/data-sources/onboard': {
      id: '/_app/data-sources/onboard'
      path: '/data-sources/onboard'
      fullPath: '/data-sources/onboard'
      preLoaderRoute: typeof AppDataSourcesOnboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/data-management/mapping': {
      id: '/_app/data-management/mapping'
      path: '/data-management/mapping'
      fullPath: '/data-management/mapping'
      preLoaderRoute: typeof AppDataManagementMappingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/data-management/layers': {
      id: '/_app/data-management/layers'
      path: '/data-management/layers'
      fullPath: '/data-management/layers'
      preLoaderRoute: typeof AppDataManagementLayersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/data-management/layer-config': {
      id: '/_app/data-management/layer-config'
      path: '/data-management/layer-config'
      fullPath: '/data-management/layer-config'
      preLoaderRoute: typeof AppDataManagementLayerConfigRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/data-management/db-mapping': {
      id: '/_app/data-management/db-mapping'
      path: '/data-management/db-mapping'
      fullPath: '/data-management/db-mapping'
      preLoaderRoute: typeof AppDataManagementDbMappingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/users': {
      id: '/_app/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AppAdminUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/settings': {
      id: '/_app/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AppAdminSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/roles': {
      id: '/_app/admin/roles'
      path: '/admin/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AppAdminRolesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/permissions': {
      id: '/_app/admin/permissions'
      path: '/admin/permissions'
      fullPath: '/admin/permissions'
      preLoaderRoute: typeof AppAdminPermissionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/health': {
      id: '/_app/admin/health'
      path: '/admin/health'
      fullPath: '/admin/health'
      preLoaderRoute: typeof AppAdminHealthRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/audit': {
      id: '/_app/admin/audit'
      path: '/admin/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AppAdminAuditRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppAdminAuditRoute: typeof AppAdminAuditRoute
  AppAdminHealthRoute: typeof AppAdminHealthRoute
  AppAdminPermissionsRoute: typeof AppAdminPermissionsRoute
  AppAdminRolesRoute: typeof AppAdminRolesRoute
  AppAdminSettingsRoute: typeof AppAdminSettingsRoute
  AppAdminUsersRoute: typeof AppAdminUsersRoute
  AppDataManagementDbMappingRoute: typeof AppDataManagementDbMappingRoute
  AppDataManagementLayerConfigRoute: typeof AppDataManagementLayerConfigRoute
  AppDataManagementLayersRoute: typeof AppDataManagementLayersRoute
  AppDataManagementMappingRoute: typeof AppDataManagementMappingRoute
  AppDataSourcesOnboardRoute: typeof AppDataSourcesOnboardRoute
  AppEntitiesEntityRoute: typeof AppEntitiesEntityRoute
  AppEntitiesRepresentativesRoute: typeof AppEntitiesRepresentativesRoute
  AppInsightsAnalyticsRoute: typeof AppInsightsAnalyticsRoute
  AppInsightsDashboardsRoute: typeof AppInsightsDashboardsRoute
  AppInsightsReportsRoute: typeof AppInsightsReportsRoute
  AppMetadataTemplatesRoute: typeof AppMetadataTemplatesRoute
  AppMetadataValidationRoute: typeof AppMetadataValidationRoute
  AppOperationsCreateScheduleRoute: typeof AppOperationsCreateScheduleRoute
  AppOperationsDeliveriesRoute: typeof AppOperationsDeliveriesRoute
  AppOperationsJobsRoute: typeof AppOperationsJobsRoute
  AppOperationsManageSchedulesRoute: typeof AppOperationsManageSchedulesRoute
  AppOperationsSchedulesRoute: typeof AppOperationsSchedulesRoute
  AppOperationsWorkflowRoute: typeof AppOperationsWorkflowRoute
  AppQualityErrorsRoute: typeof AppQualityErrorsRoute
  AppQualityMonitorRoute: typeof AppQualityMonitorRoute
  AppQualityRulesRoute: typeof AppQualityRulesRoute
  AppToolsApiRoute: typeof AppToolsApiRoute
  AppToolsAutomationRoute: typeof AppToolsAutomationRoute
  AppToolsConnectorsRoute: typeof AppToolsConnectorsRoute
  AppDataSourcesIndexRoute: typeof AppDataSourcesIndexRoute
  AppMetadataIndexRoute: typeof AppMetadataIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppAdminAuditRoute: AppAdminAuditRoute,
  AppAdminHealthRoute: AppAdminHealthRoute,
  AppAdminPermissionsRoute: AppAdminPermissionsRoute,
  AppAdminRolesRoute: AppAdminRolesRoute,
  AppAdminSettingsRoute: AppAdminSettingsRoute,
  AppAdminUsersRoute: AppAdminUsersRoute,
  AppDataManagementDbMappingRoute: AppDataManagementDbMappingRoute,
  AppDataManagementLayerConfigRoute: AppDataManagementLayerConfigRoute,
  AppDataManagementLayersRoute: AppDataManagementLayersRoute,
  AppDataManagementMappingRoute: AppDataManagementMappingRoute,
  AppDataSourcesOnboardRoute: AppDataSourcesOnboardRoute,
  AppEntitiesEntityRoute: AppEntitiesEntityRoute,
  AppEntitiesRepresentativesRoute: AppEntitiesRepresentativesRoute,
  AppInsightsAnalyticsRoute: AppInsightsAnalyticsRoute,
  AppInsightsDashboardsRoute: AppInsightsDashboardsRoute,
  AppInsightsReportsRoute: AppInsightsReportsRoute,
  AppMetadataTemplatesRoute: AppMetadataTemplatesRoute,
  AppMetadataValidationRoute: AppMetadataValidationRoute,
  AppOperationsCreateScheduleRoute: AppOperationsCreateScheduleRoute,
  AppOperationsDeliveriesRoute: AppOperationsDeliveriesRoute,
  AppOperationsJobsRoute: AppOperationsJobsRoute,
  AppOperationsManageSchedulesRoute: AppOperationsManageSchedulesRoute,
  AppOperationsSchedulesRoute: AppOperationsSchedulesRoute,
  AppOperationsWorkflowRoute: AppOperationsWorkflowRoute,
  AppQualityErrorsRoute: AppQualityErrorsRoute,
  AppQualityMonitorRoute: AppQualityMonitorRoute,
  AppQualityRulesRoute: AppQualityRulesRoute,
  AppToolsApiRoute: AppToolsApiRoute,
  AppToolsAutomationRoute: AppToolsAutomationRoute,
  AppToolsConnectorsRoute: AppToolsConnectorsRoute,
  AppDataSourcesIndexRoute: AppDataSourcesIndexRoute,
  AppMetadataIndexRoute: AppMetadataIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
